### ISSUE TITLE
Projectile is Crashing blender

### ISSUE THREAD

**Issue by JayE094** [natecraddock/projectile#15]
this is what my startup looks like, PS: it still crashes in 2.90 official
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

```
C:\Users\Jay>"Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\blender.exe"
Read prefs: C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Users\Jay\Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\2.83\python
module changed on disk: 'C:\\Users\\Jay\\Desktop\\Ttrying_Test_Builds\\2.8 Beta Version\\NewBeta\\blender-2.83-e8dd8c2829f3-windows64\\2.83\\scripts\\addons\\object_print3d_utils\\__init__.py' reloading...
power_sequencer.operators
Warning: class POWER_SEQUENCER_OT_merge_from_scene_strip contains a property which should be an annotation!
C:\Users\Jay\Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\2.83\scripts\addons\power_sequencer\__init__.py:70
    assign as a type annotation: POWER_SEQUENCER_OT_merge_from_scene_strip.delete_scene
bpy.utils.register_tool: could not find 'after' {'builtin.cut'}
Registered Power Sequencer with 74 modules
PROXIFY HANDLER: register: "proxify_pre_render" @persistent
PROXIFY HANDLER: register: "proxify_post_render" @persistent
PROXIFY HANDLER: register: "proxify_view_detect_81" @persistent (2.81+)
ValueError: OBJECT_OT_add_outline.bl_property 'object_outliner' not found
cmolcore imported with success! v1.08
Registered Carver
register_class(...):
Warning: 'MotionTrailPanel' doesn't contain '_PT_' with prefix & suffix
WARN (bpy.rna): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\python\intern\bpy_rna.c:1479 pyrna_enum_to_py: current value '0' matches no enum in 'BlenderCloudProjectGroup', '', 'project'
register_class(...):
Warning: 'menu_MT_create_rigidbodys' doesn't have upper case alpha-numeric prefix
Warning: class RIGIDBODY_OT_on_bones contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rigid_bodys_gen\__init__.py:1273
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_shape
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_dim
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_mass
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_friction
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_bounciness
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_translation
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_rotation
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_rootbody_passive
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_rootbody_animated
    assign as a type annotation: RIGIDBODY_OT_on_bones.p_rb_parent_armature
Warning: class RIGIDBODY_OT_physics contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rigid_bodys_gen\__init__.py:1273
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_shape
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_dim
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_mass
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_friction
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_bounciness
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_translation
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_rotation
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_rootbody_animated
    assign as a type annotation: RIGIDBODY_OT_physics.p_rb_parent_armature
Warning: class RIGIDBODY_OT_joints contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rigid_bodys_gen\__init__.py:1273
    assign as a type annotation: RIGIDBODY_OT_joints.joint_type
    assign as a type annotation: RIGIDBODY_OT_joints.joint_dim
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_x
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_y
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_z
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_x_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_y_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_z_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_x_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_y_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Axis_limit_z_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_x
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_y
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_z
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_x_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_y_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_z_lower
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_x_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_y_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_Angle_limit_z_upper
    assign as a type annotation: RIGIDBODY_OT_joints.joint_use_spring_x
    assign as a type annotation: RIGIDBODY_OT_joints.joint_use_spring_y
    assign as a type annotation: RIGIDBODY_OT_joints.joint_use_spring_z
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_stiffness_x
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_stiffness_y
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_stiffness_z
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_damping_x
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_damping_y
    assign as a type annotation: RIGIDBODY_OT_joints.joint_spring_damping_z
    assign as a type annotation: RIGIDBODY_OT_joints.p_rb_parent_armature
Warning: class RIGIDBODY_OT_physics_joints contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rigid_bodys_gen\__init__.py:1273
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_shape
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_dim
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_mass
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_friction
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_bounciness
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_translation
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_rotation
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_add_pole_rootbody
    assign as a type annotation: RIGIDBODY_OT_physics_joints.p_rb_parent_armature
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_type
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_dim
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_x
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_y
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_z
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_x_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_y_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_z_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_x_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_y_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Axis_limit_z_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_x
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_y
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_z
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_x_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_y_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_z_lower
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_x_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_y_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_Angle_limit_z_upper
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_use_spring_x
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_use_spring_y
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_use_spring_z
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_stiffness_x
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_stiffness_y
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_stiffness_z
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_damping_x
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_damping_y
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_spring_damping_z
    assign as a type annotation: RIGIDBODY_OT_physics_joints.joint_constraint_object
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Jay\Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\2.83\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Jay\Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\2.83\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jewelcraft\mod_update\lib.py", line 84, in _update_check
    save_state = _save_state_get()
  File "C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jewelcraft\mod_update\lib.py", line 44, in _save_state_get
    last_check = datetime.date.fromtimestamp(data["last_check"])
TypeError: an integer is required (got type str)

Warning: class SketchfabBrowserProps contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: SketchfabBrowserProps.query
    assign as a type annotation: SketchfabBrowserProps.pbr
    assign as a type annotation: SketchfabBrowserProps.categories
    assign as a type annotation: SketchfabBrowserProps.face_count
    assign as a type annotation: SketchfabBrowserProps.sort_by
    assign as a type annotation: SketchfabBrowserProps.animated
    assign as a type annotation: SketchfabBrowserProps.staffpick
    assign as a type annotation: SketchfabBrowserProps.own_models
    assign as a type annotation: SketchfabBrowserProps.status
    assign as a type annotation: SketchfabBrowserProps.use_preview
    assign as a type annotation: SketchfabBrowserProps.current_key
    assign as a type annotation: SketchfabBrowserProps.has_searched_next
    assign as a type annotation: SketchfabBrowserProps.has_searched_prev
    assign as a type annotation: SketchfabBrowserProps.has_loaded_thumbnails
    assign as a type annotation: SketchfabBrowserProps.is_latest_version
    assign as a type annotation: SketchfabBrowserProps.import_status
    assign as a type annotation: SketchfabBrowserProps.is_plugin_enabled
Warning: class SketchfabLoginProps contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: SketchfabLoginProps.email
    assign as a type annotation: SketchfabLoginProps.password
    assign as a type annotation: SketchfabLoginProps.access_token
    assign as a type annotation: SketchfabLoginProps.status
    assign as a type annotation: SketchfabLoginProps.status_type
    assign as a type annotation: SketchfabLoginProps.last_username
    assign as a type annotation: SketchfabLoginProps.last_password
Warning: class SketchfabBrowserPropsProxy contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: SketchfabBrowserPropsProxy.query
    assign as a type annotation: SketchfabBrowserPropsProxy.pbr
    assign as a type annotation: SketchfabBrowserPropsProxy.categories
    assign as a type annotation: SketchfabBrowserPropsProxy.face_count
    assign as a type annotation: SketchfabBrowserPropsProxy.sort_by
    assign as a type annotation: SketchfabBrowserPropsProxy.animated
    assign as a type annotation: SketchfabBrowserPropsProxy.staffpick
    assign as a type annotation: SketchfabBrowserPropsProxy.own_models
    assign as a type annotation: SketchfabBrowserPropsProxy.is_refreshing
    assign as a type annotation: SketchfabBrowserPropsProxy.expanded_filters
Warning: class SketchfabExportProps contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: SketchfabExportProps.description
    assign as a type annotation: SketchfabExportProps.filepath
    assign as a type annotation: SketchfabExportProps.selection
    assign as a type annotation: SketchfabExportProps.private
    assign as a type annotation: SketchfabExportProps.draft
    assign as a type annotation: SketchfabExportProps.password
    assign as a type annotation: SketchfabExportProps.tags
    assign as a type annotation: SketchfabExportProps.title
Warning: class WM_OT_skfb_enable contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_skfb_enable.enable
Warning: class WM_OT_login_modal contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_login_modal.is_logging
    assign as a type annotation: WM_OT_login_modal.error
    assign as a type annotation: WM_OT_login_modal.error_message
Warning: class WM_OT_import_modal contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_import_modal.gltf_path
    assign as a type annotation: WM_OT_import_modal.uid
Warning: class WM_OT_sketchfab_view contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_sketchfab_view.model_uid
Warning: class WM_OT_sketchfab_download contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_sketchfab_download.model_uid
Warning: class WM_OT_sketchfab_login contains a property which should be an annotation!
C:\Users\Jay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630
    assign as a type annotation: WM_OT_sketchfab_login.authenticate
SLCAD register
REFRESH JIGGLE LIST
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6480B946E
Module  : C:\Users\Jay\Desktop\Ttrying_Test_Builds\2.8 Beta Version\NewBeta\blender-2.83-e8dd8c2829f3-windows64\blender.exe

C:\Users\Jay>
```

**Comment by natecraddock** [comment]
Thanks for reporting! It appears that you have a large number of addons installed. Can you first determine if the crash is part of another addon, or if it is due to some interaction between Projectile and another addon?

Just disable all your addons except projectile and open blender. If all works fine, then enable a second addon and run again. Keep going until you determine which combination causes the crash.

**Comment by JayE094** [comment]
sure i will try to locate it as soon as possible

**Comment by natecraddock** [comment]
Have not been able to replicate this. It is likely a conflict with another addon. Closing until further information is given
